package graphic.components.planning.cell;

import javafx.scene.control.ListCell;
import javafx.util.Callback;
import tollmanager.model.planning.Planning;

public interface PlanningCell {
    /**
     * Should return the text printable for the listview
     * @return text
     */
    String getText();

    boolean isWorkingHour();

    /**
     * @return the list of cell to generated by list view
     */
    ListCell<PlanningCell> getListOfCell();


    Planning getPlanning();



}
